### ISSUE TITLE
[inconsistent behaviour] DynamicSS saving all times

### ISSUE THREAD

**Issue by benneti** [JuliaDiffEq/SteadyStateDiffEq.jl#11]
The [documentation](https://docs.juliadiffeq.org/latest/types/steady_state_types.html) that the solution object of `SteadyStateProblem`  has no time information which makes sense, but when using the dynamical solver it stores the time steps as well as the states for each step.

Wouldn't it make sense for a `SteadyStateProblem` to by default use `save_everystep=false`?
I think this makes sense because this is what the name suggests and would make the behaviour when using `nlsolve` and the dynamical approach more similar.
Additionally to get the time evolution until the steady state is reached one can simply use an `ODEProblem` and  the `TerminateSteadyState` callback or explicitly set `save_everystep=true`.

**Comment by ChrisRackauckas** [comment]
Yes, it probably makes sense to handle the output more nicely here, with `save_everystep=false` and `save_first=false` defaults (which can then be overridden to see the trajectory for debugging).

**Comment by benneti** [comment]
I can create a PR if you want me to (and you think it is worth it only to change two keyword arguments)

**Comment by ChrisRackauckas** [comment]
I think it's worth it. Thanks!

**Comment by benneti** [comment]
Can it be that `save_first=false` does not take effect (also I do not find it in the documentation)?
Or did you mean that I should implement this as a keyword argument there and if it is `false` we just return `sol.u[end]`?

Also for me the test in line 44 fails because the return code is `Terminated` not `Success`, which is also what I would expect because the callback terminates the integration before reaching the final time.

On another note can you tell me whether there is a way to run the tests directly from my local copy of the repo, because the way I do it now (`add`ing the repo in a julia REPL and then running the test) seems unnecessarily complicated.

**Comment by ChrisRackauckas** [comment]
>Also for me the test in line 44 fails because the return code is Terminated not Success

Yes, looks like that never got updated.

>Can it be that save_first=false does not take effect (also I do not find it in the documentation)?

Sorry, `save_start=false`.

>On another note can you tell me whether there is a way to run the tests directly from my local copy of the repo, because the way I do it now (adding the repo in a julia REPL and then running the test) seems unnecessarily complicated.

`]dev SteadyStateDiffEq` and now you edit in your `.julia` folder, and then `]test SteadyStateDiffEq`.

**Comment by benneti** [comment]
Maybe it would also make sense to change the `terminated` retcode to `success` such that whether one uses the rootfinding or dynamical approach `success` states that the steady state was found.

**Comment by ChrisRackauckas** [comment]
Yes. Just use the utility function DiffEqBase.solution_new_retcode

**Comment by benneti** [comment]
Do you think testing whether the derivative is roughly 0 is necessary or is it fine to assume the user does not use another Callback that terminates the integration while using this problem type?

**Comment by ChrisRackauckas** [comment]
Oh yes, checking the derivative before calling it a success is probably a good idea
